Revert "Refresh lock file"
This reverts commit 24ccbbd83d05d5da52657688cf2e6ba899d062f0.

Because even though the lib built fine, it became not usable in project,
throwing `TypeError: record.factory is not a function` on runtime.