BREAKING: `modelService.delete()` does not `refetchObservableQueries()` #12584
The most common use case for `modelService.delete()` is from a page
detail, and after deletion the user is redirected to the page listing.
So there is no need to `refetchObservableQueries()` unconditionally.

# Other use cases

For other use cases we can reload specific queries like those
examples.

## Dialog

From a dialog on top of the listing page:

```ts
this.itemService
    .delete([id], {
        // Wait till we refresh the list under the dialog before closing the dialog, to avoid re-clicking on the just deleted item
        refetchQueries: [itemsQuery],
        awaitRefetchQueries: true,
    })
    .subscribe({
        next: () => {
            this.alertService.info(`Supprimé`);
            this.dialogRef.close();
        }
    });
```

## Inline deletion in listing

From a listing page where deletion is directly accessible on the row:

```ts
this.itemService.delete([id], {
    refetchQueries: [itemsQuery],
}).subscribe({
    next: () => {
        this.alertService.info(`Supprimé`);
    },
    error: () => this.deleting.delete(id),
});
```

## Bulk deleting

Bulk deleting via `NaturalAbstractList.bulkDelete()` still automatically
refetch the listing of items, but no other queries anymore.