Prevent ViewDestroyedError if user change pages too quickly
If the component is destroyed before the timeout is executed because
the user change pages very quickly, then it would raise the error:

```
ViewDestroyedError: Attempt to use a destroyed view: detectChanges
```